; Exercise 1.15: The sine of an angle (specified in radians) can be computed by making use of the approximation sinx≈xsin⁡x≈x if xx is sufficiently small, and the trigonometric identity
; sinx=3sinx3−4sin3x3
; sin⁡x=3sin⁡x3−4sin3⁡x3
; to reduce the size of the argument of sin. (For purposes of this exercise an angle is considered “sufficiently small” if its magnitude is not greater than 0.1 radians.) These ideas are incorporated in the following procedures:

; (define (cube x) (* x x x))
; (define (p x) (- (* 3 x) (* 4 (cube x))))
; (define (sine angle)
;    (if (not (> (abs angle) 0.1))
;        angle
;        (p (sine (/ angle 3.0)))))
; How many times is the procedure p applied when (sine 12.15) is evaluated?
; What is the order of growth in space and number of steps (as a function of aa) used by the process generated by the sine procedure when (sine a) is evaluated?